### ISSUE TITLE
Add gitter or some similar chat tool [Feature]

### ISSUE THREAD

**Issue by spik3r** [dtobe/aietes-js#20]
It would be nice to have a chat tool to discuss implementation details & features etc more efficiently than through pull requests. Especially once the project is open source and other people contribute.

Two possible options are slack & gitter:
Slack seems to have a restriction to the number of users on the free plan and Gitter just requires the project to be open source (so this may be the better option)
[gitter](
https://gitter.im/home#createcommunity)

**Comment by dtobe** [comment]
spik3r has done this already.
https://gitter.im/aietes-js/community
Also linked on home page.
